const symbols=["🎮","🎲","🕹️","👾","🚀","⭐","🎯","💎"],storageKey="ayazArcadeStats";
const defaults={memoryBest:0,reactionBest:null,totalWins:0,bestStreak:0};
const state={...defaults,memoryCards:[],flipped:[],matched:0,score:0,tries:0,number:null,reactionTimer:null,reactionReady:false,reactionStart:0,sound:true};
const $=id=>document.getElementById(id);
const els={board:$('memoryBoard'),memoryScore:$('memoryScore'),memoryStatus:$('memoryStatus'),reaction:$('reactionBtn'),reactionStatus:$('reactionStatus'),reactionScore:$('reactionScore'),guess:$('guessInput'),guessBtn:$('guessBtn'),guessStatus:$('guessStatus'),guessScore:$('guessScore'),streak:$('bestStreak'),fastest:$('fastestReaction'),wins:$('totalWins'),leaders:$('leaderboardList'),toast:$('toast')};
function load(){try{Object.assign(state,defaults,JSON.parse(localStorage.getItem(storageKey)||'{}'));state.sound=localStorage.getItem('ayazSound')!=='off'}catch(e){};renderStats()}
function save(){localStorage.setItem(storageKey,JSON.stringify({memoryBest:state.memoryBest,reactionBest:state.reactionBest,totalWins:state.totalWins,bestStreak:state.bestStreak}));renderStats()}
function renderStats(){els.streak.textContent=state.bestStreak;els.wins.textContent=state.totalWins;els.fastest.textContent=state.reactionBest?`${state.reactionBest} ms`:'--';els.leaders.innerHTML=`<li>Memory master — ${state.memoryBest} pts</li><li>Reflex king — ${state.reactionBest||0} ms</li><li>Lucky guesser — ${state.totalWins} wins</li>`}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function beep(freq=500,duration=.08){if(!state.sound)return;try{const c=new(window.AudioContext||window.webkitAudioContext)(),o=c.createOscillator(),g=c.createGain();o.frequency.value=freq;o.connect(g);g.connect(c.destination);g.gain.value=.035;o.start();o.stop(c.currentTime+duration)}catch(e){}}
let toastTimer;function toast(message){els.toast.textContent=message;els.toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>els.toast.classList.remove('show'),2200)}
function newMemory(){state.memoryCards=shuffle([...symbols,...symbols]).map((symbol,i)=>({id:i,symbol,matched:false}));state.flipped=[];state.matched=0;state.score=0;els.memoryScore.textContent='0 pts';els.memoryStatus.textContent='Find all 8 pairs with as few flips as possible.';els.board.innerHTML='';state.memoryCards.forEach(card=>{const b=document.createElement('button');b.type='button';b.className='memory-card';b.textContent='?';b.setAttribute('aria-label','Hidden memory card');b.onclick=()=>flip(b,card);els.board.appendChild(b)})}
function flip(button,card){if(state.flipped.length===2||card.matched||state.flipped.includes(card))return;button.classList.add('is-flipped');button.textContent=card.symbol;button.setAttribute('aria-label',card.symbol);state.flipped.push(card);beep(440);if(state.flipped.length<2)return;const[a,b]=state.flipped;if(a.symbol===b.symbol){a.matched=b.matched=true;state.matched++;state.score+=100;els.memoryScore.textContent=`${state.score} pts`;[...els.board.children].filter(x=>x.textContent===a.symbol).forEach(x=>x.classList.add('is-matched'));state.flipped=[];beep(760);if(state.matched===symbols.length){state.memoryBest=Math.max(state.memoryBest,state.score);state.bestStreak++;els.memoryStatus.textContent='Board cleared! Excellent memory.';els.memoryStatus.className='status-text success';toast('Memory board cleared!');save()}}else{state.bestStreak=0;els.memoryStatus.textContent='Not a match — keep looking.';setTimeout(()=>{[...els.board.children].forEach(x=>{if(!x.classList.contains('is-matched')){x.textContent='?';x.classList.remove('is-flipped');x.setAttribute('aria-label','Hidden memory card')}});state.flipped=[]},650);save()}}
function startReaction(){els.reaction.disabled=true;els.reaction.className='reaction-btn waiting';els.reaction.textContent='Wait for green...';els.reactionStatus.textContent='Stay focused — do not click early.';state.reactionReady=false;state.reactionTimer=setTimeout(()=>{state.reactionReady=true;state.reactionStart=performance.now();els.reaction.disabled=false;els.reaction.className='reaction-btn ready';els.reaction.textContent='CLICK!';els.reactionStatus.textContent='Now!';beep(900,.12)},1000+Math.random()*2500)}
function reactionClick(){if(!state.reactionReady){if(els.reaction.disabled)return;startReaction();return}const ms=Math.round(performance.now()-state.reactionStart);state.reactionBest=!state.reactionBest?ms:Math.min(state.reactionBest,ms);els.reactionScore.textContent=`${ms} ms`;els.reactionStatus.textContent=`${ms} ms — ${ms<300?'Lightning fast!':'Good run!'} Press to try again.`;els.reaction.className='reaction-btn';els.reaction.textContent='Press to start';state.reactionReady=false;state.reactionStart=0;beep(700);save()}
function newGuess(){state.number=Math.floor(Math.random()*100)+1;state.tries=0;els.guess.value='';els.guessScore.textContent='0 tries';els.guessStatus.textContent='A mystery number is waiting.';els.guessStatus.className='status-text'}
function guess(){const n=Number(els.guess.value);if(!Number.isInteger(n)||n<1||n>100){els.guessStatus.textContent='Enter a whole number between 1 and 100.';els.guessStatus.className='status-text danger';return}state.tries++;els.guessScore.textContent=`${state.tries} tries`;if(n===state.number){state.totalWins++;els.guessStatus.textContent=`Correct! You solved it in ${state.tries} tries.`;els.guessStatus.className='status-text success';toast('Secret number solved!');beep(880,.15);save();setTimeout(newGuess,1400)}else{els.guessStatus.textContent=n<state.number?'Too low. Try higher.':'Too high. Try lower.';els.guessStatus.className='status-text';els.guess.value='';els.guess.focus();beep(260)}}
function reset(){clearTimeout(state.reactionTimer);Object.assign(state,defaults);state.sound=localStorage.getItem('ayazSound')!=='off';newMemory();newGuess();els.reaction.disabled=false;els.reaction.className='reaction-btn';els.reaction.textContent='Press to start';els.reactionStatus.textContent='Wait for the green signal.';localStorage.removeItem(storageKey);renderStats();toast('Session reset')}
els.reaction.onclick=reactionClick;els.guessBtn.onclick=guess;els.guess.onkeydown=e=>{if(e.key==='Enter')guess()};$('memoryResetBtn').onclick=newMemory;$('resetAllBtn').onclick=reset;$('soundBtn').onclick=()=>{state.sound=!state.sound;localStorage.setItem('ayazSound',state.sound?'on':'off');$('soundBtn').textContent=state.sound?'🔊':'🔇';toast(state.sound?'Sound on':'Sound off')};$('themeBtn').onclick=()=>{document.body.classList.toggle('light-mode');$('themeBtn').textContent=document.body.classList.contains('light-mode')?'🌙':'☀️'};
load();$('soundBtn').textContent=state.sound?'🔊':'🔇';newMemory();newGuess();renderStats();
